FiorelloBack/Controllers/FlowerController.cs
using FiorelloBack.DAL;
using FiorelloBack.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FiorelloBack.Controllers
{
    public class FlowerController : Controller
    {
        private readonly AppDbContext _context;
        public FlowerController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Details(int id,int categoryId)
        {
            Flower flower = _context.Flowers.Include(f=>f.Campaign).Include(f=>f.FlowerImages).Include(f=>f.FlowerCategories).ThenInclude(fc=>fc.Category).FirstOrDefault(f => f.Id == id);

            ViewBag.RelatedFlower = _context.Flowers.Include(f=>f.FlowerCategories).Include(x=>x.FlowerImages).Include(x=>x.Campaign).Where(f => f.FlowerCategories.FirstOrDefault().CategoryId == categoryId && f.Id!= id).ToList();
            return View(flower);
        }
      
    }
}

FiorelloBack/Views/Shared/_FLowerPartialView.cshtml
@model List<Flower>

@foreach (var flower in Model)
{
    <div data-aos-offset="100"
         class="product col-lg-3 col-md-6
                     @foreach (var flowerCategory in flower.FlowerCategories)
                     {
                         @(flowerCategory.Category.Name.ToLower()+" ")
                     }
                     all">
        <div class="productImage">
            @foreach (var image in flower.FlowerImages)
            {
                if (image.IsMain && image.Image.Contains("https://"))
                {
                    <a asp-controller="Flower" asp-action="Details" asp-route-id="@flower.Id" asp-route-categoryId="@flower.FlowerCategories.FirstOrDefault().CategoryId">
                        <img src="@image.Image" alt="">
                    </a>
                }
                if (image.IsMain)
                {
                    <a asp-controller="Flower" asp-action="Details" asp-route-id="@flower.Id" asp-route-categoryId="@flower.FlowerCategories.FirstOrDefault().CategoryId">
                        <img src="~/assets/images/@image.Image" alt="">
                    </a>
                }

            }


        </div>
        <div class="productTitle">
            <p>@flower.Name</p>
        </div>
        <div class="productPrice">
            @if (flower.CampaignId == null)
            {
                <span class="addToCardBtn" data-id="@flower.Id">Add to cart</span><span>$</span><span>@flower.Price</span>
            }
            else
            {
                <span class="addToCardBtn" data-id="5">Add to cart</span> <span style="text-decoration: line-through;">@flower.Price</span>
                <span>$</span><span>@(flower.Price*(100-flower.Campaign.Dicount)/100)</span>
            }

        </div>
        <div class="addToCart">

        </div>

    </div>
}